#!/bin/bash

echo =====================================================
echo See https://github.com/tyankatsu0105/sandbox-conventional-changelog/pulls
echo ============================================